#!/bin/sh

branch_name=$(git rev-parse --abbrev-ref HEAD)

if [ "$branch_name" = "main" ]; then
    echo "You are not allowed to push directly to the main branch. Please use a feature branch and create a pull request."
    exit 1
fi
